FROM rafkhan/rangle-node:14.04-4.2.2

# Docker 1.6.2

# application installs
RUN sudo apt-get update && sudo apt-get -y install git wget \
  wget -qO- https://get.docker.com/ | sed 's/lxc-docker/lxc-docker-1.9.0/' | sh

RUN mkdir /home/app
COPY . /home/app/
RUN cd /home/app/; npm install


## Expose the ports
EXPOSE 9090

CMD ["/home/app/serve.sh"]
