FROM rangle/clusternator-node-5:latest

# Set up a place for your applications to live.
RUN mkdir /home/app
COPY . /home/app/
RUN chown -R swuser:swuser /home/app

# install the application
USER swuser
RUN cd /home/app/; npm set progress=false; npm install

## Expose the ports
EXPOSE 3000

CMD ["/home/app/.clusternator/serve.sh"]
