FROM rafkhan/rangle-node:14.04-4.3.2

# setup user
USER root
RUN mkdir /home/swuser
RUN groupadd -r swuser -g 433 && \
useradd -u 431 -r -g swuser -d /home/swuser -s /sbin/nologin \
-c "Docker image user" swuser && \
chown -R swuser:swuser /home/swuser

# install tools
RUN sudo apt-get update && sudo apt-get install -y git build-essential

# setup the application
RUN mkdir /home/app
COPY . /home/app/
RUN chown -R swuser:swuser /home/app

# install the application
USER swuser
RUN cd /home/app/; npm set progress=false; npm install


## Expose the ports
EXPOSE 3000

USER swuser
CMD ["/home/app/$CLUSTERNATOR_DIR/serve.sh"]
