FROM rafkhan/rangle-node:14.04-4.2.3

RUN sudo apt-get update && sudo apt-get install -y git build-essential

RUN mkdir /home/app
COPY . /home/app/
RUN cd /home/app/; npm install


## Expose the ports
EXPOSE 3000

CMD ["/home/app/$CLUSTERNATOR_DIR/serve.sh"]
