#!/bin/sh

if clusternator private-diff;
then
  echo "No Changes to private files, skipping encryption.  Please ensure your \
  private folder is ignored by version controlled"
else
  clusternator make-private -p $CLUSTERNATOR_PASS
  clusternator private-checksum
  git add ./clusternator.tar.gz.asc
  # note adding .private-checksum to .clusternator litarally
  # is _not_ good practice as .clusternator is "configurable"
  git add ./.clusternator/.private-checksum 
fi
